server {
    listen 80;
    root /var/www/html/public;
    index index.php index.html;

    client_max_body_size 20M;

    location /storage/ {
        add_header 'Access-Control-Allow-Origin' '*' always;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
}
